//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpInsuranceQuoteWebAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int Id { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string EAddress { get; set; }
        public Nullable<int> Estimation { get; set; }
    }
}
